window.WORDS = [
  { english: "temptation", russian: "искушение" },
  { english: "ample", russian: "обильный; просторный" },
  { english: "mutilate", russian: "калечить" },
  { english: "noodles", russian: "лапша" },
  { english: "casserole", russian: "запеканка" },
  { english: "medley", russian: "смесь; ассорти; попурри" },
  { english: "cattle", russian: "крупный рогатый скот" },
  { english: "mutilated", russian: "искалеченный" },
  { english: "chosen", russian: "избранный" },
  { english: "cost", russian: "стоить; цена" },
  { english: "fit", russian: "подходить; быть в форме" },
  {
    english: "get",
    displayEnglish: "get - got - gotten",
    acceptedAnswers: ["get got gotten"],
    russian: "получать; доставать"
  },
  { english: "hit on", russian: "флиртовать" },
  { english: "movie", russian: "фильм; кино" },
  { english: "film", acceptedAnswers: ["the film"], russian: "пленка; фильм" },
  { english: "couch", russian: "диван" },
  { english: "go to hell", russian: "иди к черту" },
  { english: "fuck you", russian: "да пошел ты" },
  { english: "to hell with that", russian: "к черту это" },
  { english: "maintain", russian: "поддерживать; сохранять" },
  { english: "admire", russian: "восхищаться" },
  { english: "envy", russian: "завидовать; зависть" },
  { english: "lifespan", russian: "срок жизни" },
  { english: "contribute", russian: "вносить вклад; способствовать" },
  { english: "prevention", russian: "предотвращение" },
  { english: "maturation", russian: "созревание" },
  { english: "pissed off", russian: "очень злой; взбешенный" },
  { english: "powder", russian: "порошок; пыль" },
  { english: "pot", russian: "горшок; котелок" },
  { english: "stinking", russian: "вонючий" },
  { english: "cast", displayEnglish: "to cast", acceptedAnswers: ["to cast"], russian: "бросать; отбрасывать" },
  { english: "possess", russian: "обладать" },
  { english: "wealth", russian: "богатство" },
  { english: "gather", displayEnglish: "to gather", acceptedAnswers: ["to gather"], russian: "собирать" },
  { english: "offensive", russian: "оскорбительный; обидный" },
  { english: "commitment", russian: "обязательство" },
  { english: "therefore", russian: "поэтому; следовательно" },
  { english: "vicarious", russian: "косвенный; переживаемый через другого" },
  { english: "initial", russian: "начальный; первоначальный" },
  { english: "substitute", russian: "заменитель; заместитель" },
  { english: "nauseous", russian: "тошнотворный; отвратительный" },
  { english: "sawed", russian: "пилил; распиливал" },
  { english: "sinew", russian: "сухожилие; мускулатура" },
  { english: "masterpiece", russian: "шедевр" },
  { english: "adjacent", russian: "смежный; соседний" },
  { english: "investigate", russian: "расследовать; исследовать" },
  { english: "recruitment", russian: "набор; подбор персонала" },
  { english: "stir", russian: "помешивать" },
  { english: "lakeshore", russian: "берег озера" },
  { english: "rowboat", russian: "лодка на веслах" },
  { english: "sailboat", russian: "парусная лодка; яхта" },
  { english: "catch", russian: "ловить; поймать" },
  { english: "crash", russian: "грохот; авария" },
  { english: "entire", russian: "весь; целый" },
  { english: "punch", russian: "удар кулаком; бить кулаком" },
  { english: "get rid of", russian: "избавляться от" },
  { english: "lead", russian: "свинец" },
  { english: "pay a visit", russian: "нанести визит" },
  { english: "dandelion", russian: "одуванчик" },
  { english: "swamp", russian: "болото" },
  { english: "puddle", russian: "лужа" },
  { english: "shallow", russian: "мелкий; неглубокий" },
  { english: "shallow person", russian: "поверхностный человек" },
  { english: "asshole", russian: "мудак" },
  { english: "target", russian: "цель" },
  { english: "god bless you", russian: "будь здоров" },
  { english: "break a leg", russian: "удачи" },
  { english: "pupil", russian: "ученик" },
  { english: "cereal", russian: "хлопья; злак" },
  { english: "seeds", russian: "семена" },
  { english: "pine", russian: "сосна" },
  { english: "cousin", russian: "двоюродный брат; двоюродная сестра" },
  { english: "brother-in-law", russian: "шурин; деверь; зять" },
  { english: "sister-in-law", russian: "золовка; невестка" },
  { english: "cottage cheese", russian: "творог" },
  { english: "chest", russian: "грудь" },
  { english: "cream", russian: "сливки; крем" },
  { english: "sour cream", russian: "сметана" },
  { english: "whipped cream", russian: "взбитые сливки" },
  { english: "cutlet", russian: "котлета" },
  { english: "bush", russian: "куст" },
  { english: "sprinkles", acceptedAnswers: ["sprinklers"], russian: "кондитерская посыпка" },
  { english: "slides", russian: "горки; слайды" },
  {
    english: "to pound",
    displayEnglish: "to pound / pounder",
    acceptedAnswers: ["pounder"],
    russian: "толочь; дробить"
  },
  {
    english: "to persecute",
    russian: "преследовать; подвергать гонениям; досаждать"
  },
  { english: "tough love", russian: "суровая любовь" },
  { english: "to shun", russian: "избегать; сторониться" },
  { english: "to snip", russian: "резать; отрезать" },
  { english: "sober", russian: "трезвый; сдержанный; серьезный" },
  { english: "wreck", russian: "крушение; авария; испортить" },
  {
    english: "bunch",
    displayEnglish: "bunch / to bunch",
    acceptedAnswers: ["to bunch"],
    russian: "куча; группа; собирать в кучу"
  },
  { english: "sequence", russian: "последовательность; порядок" },
  { english: "North Pole", russian: "Северный полюс" },
  { english: "South Pole", russian: "Южный полюс" },
  { english: "equator", russian: "экватор" },
  { english: "crow", russian: "ворона" },
  { english: "Mars", russian: "Марс" },
  { english: "Earth", russian: "Земля" },
  { english: "Venus", russian: "Венера" },
  { english: "Jupiter", russian: "Юпитер" },
  { english: "moon", russian: "Луна" },
  { english: "Earth's core", russian: "ядро Земли" },
  { english: "ozone layer", russian: "озоновый слой" },
  { english: "incongruity", russian: "несоответствие" },
  { english: "loaf", russian: "булка; батон" },
  { english: "cupboard", russian: "буфет; шкаф" },
  { english: "to loaf", russian: "бездельничать; слоняться" },
  { english: "study", russian: "кабинет" },
  { english: "animal", russian: "животное; скот" },
  { english: "filthy animal", russian: "грязное животное" },
  { english: "pale", russian: "бледный; светлый" },
  { english: "cozy", russian: "уютный" },
  { english: "mild person", russian: "мягкий человек" },
  { english: "warm personality", russian: "теплый характер" },
  { english: "expressive", russian: "выразительный; эмоциональный" },
  { english: "glossy", russian: "глянцевый; блестящий" },
  { english: "rewarding", russian: "приносящий удовлетворение" },
  { english: "give off", russian: "испускать; отдавать" },
  {
    english: "tap",
    displayEnglish: "tap / to tap",
    acceptedAnswers: ["to tap"],
    russian: "кран; постукивать"
  },
  { english: "sticky", russian: "липкий; клейкий" },
  { english: "inner", russian: "внутренний" },
  { english: "surpassing", russian: "превосходящий; исключительный" },
  { english: "to retard", russian: "тормозить; задерживать" },
  { english: "to occur", russian: "случаться; происходить" },
  {
    english: "trap",
    displayEnglish: "trap / to trap",
    acceptedAnswers: ["to trap"],
    russian: "ловушка; капкан; заманивать"
  },
  { english: "bother", russian: "доставать; беспокоить" },
  { english: "survey", russian: "опрос; исследование" },
  { english: "twerp", russian: "придурок" },
  { english: "exposure", russian: "воздействие; разоблачение" },
  { english: "broadly", russian: "в широком смысле; в целом" },
  { english: "coursework", russian: "курсовая работа" },
  {
    english: "workflow",
    acceptedAnswers: ["work flow", "workflows"],
    russian: "рабочий процесс; схема работы"
  },
  { english: "seagull", acceptedAnswers: ["seagulls"], russian: "чайка" },
  { english: "shore", russian: "берег; побережье; край" },
  { english: "Northern Hemisphere", russian: "северное полушарие" },
  { english: "Southern Hemisphere", russian: "южное полушарие" },
  { english: "Eastern Hemisphere", russian: "восточное полушарие" },
  { english: "Western Hemisphere", russian: "западное полушарие" },
  { english: "Mercury", russian: "Меркурий" },
  { english: "Saturn", russian: "Сатурн" },
  { english: "Uranus", russian: "Уран" },
  { english: "Neptune", russian: "Нептун" },
  {
    english: "armour",
    displayEnglish: "armour / to armour",
    acceptedAnswers: ["armor", "to armor", "to armour"],
    russian: "броня; доспехи; защищать"
  },
  { english: "impenetrable", russian: "непроницаемый; непробиваемый" },
  {
    english: "sip",
    displayEnglish: "sip / to sip",
    acceptedAnswers: ["to sip"],
    russian: "глоток; пить маленькими глотками"
  },
  { english: "clubhouse", russian: "клубный дом" },
  {
    english: "hammer",
    displayEnglish: "hammer / to hammer",
    acceptedAnswers: ["to hammer"],
    russian: "молоток; бить; колотить"
  },
  { english: "disposal", russian: "удаление; утилизация; распоряжение" },
  { english: "blasphemous", russian: "богохульный; кощунственный" },
  { english: "dopefiend", russian: "наркоман; торчок" },
  {
    english: "jimmy",
    displayEnglish: "jimmy / to jimmy",
    acceptedAnswers: ["to jimmy"],
    russian: "взламывать; открывать силой"
  },
  { english: "to snap", russian: "щелкать; треснуть" },
  { english: "gross", russian: "мерзкий; грубый; отвратительный" },
  { english: "lame", russian: "хромой; слабый; тупой" },
  { english: "foreman", russian: "мастер; бригадир" },
  { english: "adverse", russian: "неблагоприятный; вредный" },
  { english: "eternity", russian: "вечность; бесконечность" },
  { english: "immature", russian: "незрелый; инфантильный" },
  { english: "skylarking", russian: "дурачество; баловство" },
  { english: "to skylark", russian: "дурачиться; резвиться" },
  { english: "tomfoolery", russian: "дурачество; шалости" },
  { english: "root", russian: "корень; основа; источник" },
  { english: "gossip", russian: "сплетни; слухи" },
  { english: "eager", russian: "стремящийся; жаждущий" },
  { english: "dove", russian: "голубь" },
  { english: "to beat", russian: "бить; побеждать" },
  { english: "beverage", russian: "напиток" },
  { english: "to acquaint", russian: "знакомить; осведомлять" },
  { english: "curfew", russian: "комендантский час" },
  { english: "sturdy", russian: "крепкий; прочный; надежный" },
  { english: "to hop in", russian: "быстро сесть; запрыгнуть внутрь" },
  { english: "to snuggle", russian: "прижиматься; уютно обниматься" },
  {
    english: "consent",
    displayEnglish: "consent / to consent",
    acceptedAnswers: ["to consent"],
    russian: "согласие; разрешение; соглашаться"
  },
  { english: "to thrive", russian: "процветать; расцветать" },
  { english: "appliance", russian: "бытовая техника" },
  { english: "lark", russian: "жаворонок" },
  { english: "wren", russian: "крапивник" },
  { english: "nest", russian: "гнездо" },
  { english: "cushion", acceptedAnswers: ["cushions"], russian: "диванная подушка" },
  { english: "peculiar", russian: "странный; необычный" },
  { english: "hazard", russian: "опасность; риск; угроза" },
  { english: "to nag", russian: "пилить; надоедать; ворчать" },
  { english: "tether", russian: "привязь; веревка" },
  { english: "particularly", russian: "особенно; в частности" },
  { english: "ongoing work", russian: "текущая работа" },
  { english: "disruption", russian: "нарушение; сбой" },
  { english: "slippery", russian: "скользкий" },
  { english: "bud", russian: "бутон" },
  { english: "lug", russian: "тащить; волочь" },
  { english: "valley", russian: "долина" },
  { english: "raiding", russian: "совершающий налет; нападающий" },
  { english: "defense", acceptedAnswers: ["defence"], russian: "защита; оборона" },
  { english: "mud", russian: "грязь; слякоть; ил" },
  { english: "savage", russian: "дикий; жестокий; свирепый" },
  { english: "intent", russian: "намерение; умысел" },
  { english: "indeed", russian: "действительно; в самом деле" },
  { english: "to untie", russian: "развязывать; отвязать" },
  { english: "customary", russian: "обычный; принятый; традиционный" },
  { english: "to kneel", russian: "встать на колени; преклонить колени" },
  { english: "tribe", russian: "племя; род" },
  { english: "heretic", russian: "еретик" },
  { english: "to condemn", russian: "осуждать; приговорить" },
  { english: "to herald", russian: "возвещать; предвещать; объявлять" },
  { english: "berry", russian: "ягода" },
  { english: "blizzard", russian: "метель; вьюга; снежный буран" },
  { english: "ancestor", russian: "предок; прародитель" },
  { english: "despite", russian: "несмотря на; вопреки" },
  { english: "to strike", russian: "ударять; поражать; наносить удар" },
  { english: "kite", russian: "воздушный змей; коршун" },
  { english: "magpie", russian: "сорока" },
  { english: "crane", russian: "журавль" },
  { english: "grief", russian: "горе; скорбь" },
  { english: "to grieve", russian: "горевать; скорбеть" },
  { english: "to get lost", russian: "заблудиться; потеряться" },
  { english: "complacency", russian: "самоуспокоение; беспечность" },
  { english: "eudaimonia", russian: "счастье; благополучие" },
  { english: "contentment", russian: "удовлетворенность; довольство" },
  { english: "to reminisce", russian: "предаваться воспоминаниям" },
  { english: "ridge", russian: "хребет; гребень" },
  { english: "rut", russian: "колея; рутина" },
  { english: "to unthink", russian: "раздумать; выбросить из головы" },
  { english: "pristine", russian: "нетронутый; безупречный" },
  { english: "beechwood", russian: "буковая древесина" },
  { english: "fiddle", russian: "скрипка; обман" }
];
