window.WORDS = [
  { english: "temptation", russian: "искушение" },
  { english: "ample", russian: "обильный; просторный" },
  { english: "mutilate", russian: "калечить" },
  { english: "noodles", russian: "лапша" },
  { english: "casserole", russian: "запеканка" },
  { english: "medley", russian: "смесь; ассорти; попурри" },
  { english: "cattle", russian: "крупный рогатый скот" },
  { english: "mutilated", russian: "искалеченный" },
  { english: "chosen", russian: "избранный" },
  { english: "cost", russian: "стоить; цена" },
  { english: "fit", russian: "подходить; быть в форме" },
  {
    english: "get",
    displayEnglish: "get - got - gotten",
    acceptedAnswers: ["get got gotten"],
    russian: "получать; доставать"
  },
  { english: "hit on", russian: "флиртовать" },
  { english: "movie", russian: "фильм; кино" },
  { english: "film", acceptedAnswers: ["the film"], russian: "пленка; фильм" },
  { english: "couch", russian: "диван" },
  { english: "go to hell", russian: "иди к черту" },
  { english: "fuck you", russian: "да пошел ты" },
  { english: "to hell with that", russian: "к черту это" },
  { english: "maintain", russian: "поддерживать; сохранять" },
  { english: "admire", russian: "восхищаться" },
  { english: "envy", russian: "завидовать; зависть" },
  { english: "lifespan", russian: "срок жизни" },
  { english: "contribute", russian: "вносить вклад; способствовать" },
  { english: "prevention", russian: "предотвращение" },
  { english: "maturation", russian: "созревание" },
  { english: "pissed off", russian: "очень злой; взбешенный" },
  { english: "powder", russian: "порошок; пыль" },
  { english: "pot", russian: "горшок; котелок" },
  { english: "stinking", russian: "вонючий" },
  { english: "cast", displayEnglish: "to cast", acceptedAnswers: ["to cast"], russian: "бросать; отбрасывать" },
  { english: "possess", russian: "обладать" },
  { english: "wealth", russian: "богатство" },
  { english: "gather", displayEnglish: "to gather", acceptedAnswers: ["to gather"], russian: "собирать" },
  { english: "offensive", russian: "оскорбительный; обидный" },
  { english: "commitment", russian: "обязательство" },
  { english: "therefore", russian: "поэтому; следовательно" },
  { english: "vicarious", russian: "косвенный; переживаемый через другого" },
  { english: "initial", russian: "начальный; первоначальный" },
  { english: "substitute", russian: "заменитель; заместитель" },
  { english: "nauseous", russian: "тошнотворный; отвратительный" },
  { english: "sawed", russian: "пилил; распиливал" },
  { english: "sinew", russian: "сухожилие; мускулатура" },
  { english: "masterpiece", russian: "шедевр" },
  { english: "adjacent", russian: "смежный; соседний" },
  { english: "investigate", russian: "расследовать; исследовать" },
  { english: "recruitment", russian: "набор; подбор персонала" },
  { english: "stir", russian: "помешивать" },
  { english: "lakeshore", russian: "берег озера" },
  { english: "rowboat", russian: "лодка на веслах" },
  { english: "sailboat", russian: "парусная лодка; яхта" },
  { english: "catch", russian: "ловить; поймать" },
  { english: "crash", russian: "грохот; авария" },
  { english: "entire", russian: "весь; целый" },
  { english: "punch", russian: "удар кулаком; бить кулаком" },
  { english: "get rid of", russian: "избавляться от" },
  { english: "lead", russian: "свинец" },
  { english: "pay a visit", russian: "нанести визит" },
  { english: "dandelion", russian: "одуванчик" },
  { english: "swamp", russian: "болото" },
  { english: "puddle", russian: "лужа" },
  { english: "shallow", russian: "мелкий; неглубокий" },
  { english: "shallow person", russian: "поверхностный человек" },
  { english: "asshole", russian: "мудак" },
  { english: "target", russian: "цель" },
  { english: "god bless you", russian: "будь здоров" },
  { english: "break a leg", russian: "удачи" },
  { english: "pupil", russian: "ученик" },
  { english: "cereal", russian: "хлопья; злак" },
  { english: "seeds", russian: "семена" },
  { english: "pine", russian: "сосна" },
  { english: "cousin", russian: "двоюродный брат; двоюродная сестра" },
  { english: "brother-in-law", russian: "шурин; деверь; зять" },
  { english: "sister-in-law", russian: "золовка; невестка" },
  { english: "cottage cheese", russian: "творог" },
  { english: "chest", russian: "грудь" },
  { english: "cream", russian: "сливки; крем" },
  { english: "sour cream", russian: "сметана" },
  { english: "whipped cream", russian: "взбитые сливки" },
  { english: "cutlet", russian: "котлета" },
  { english: "bush", russian: "куст" },
  { english: "sprinkles", acceptedAnswers: ["sprinklers"], russian: "кондитерская посыпка" },
  { english: "slides", russian: "горки; слайды" },
  {
    english: "to pound",
    displayEnglish: "to pound / pounder",
    acceptedAnswers: ["pounder"],
    russian: "толочь; дробить"
  },
  {
    english: "to persecute",
    russian: "преследовать; подвергать гонениям; досаждать"
  },
  { english: "tough love", russian: "суровая любовь" },
  { english: "to shun", russian: "избегать; сторониться" },
  { english: "to snip", russian: "резать; отрезать" },
  { english: "sober", russian: "трезвый; сдержанный; серьезный" },
  { english: "wreck", russian: "крушение; авария; испортить" },
  {
    english: "bunch",
    displayEnglish: "bunch / to bunch",
    acceptedAnswers: ["to bunch"],
    russian: "куча; группа; собирать в кучу"
  },
  { english: "sequence", russian: "последовательность; порядок" },
  { english: "North Pole", russian: "Северный полюс" },
  { english: "South Pole", russian: "Южный полюс" },
  { english: "equator", russian: "экватор" },
  { english: "crow", russian: "ворона" },
  { english: "Mars", russian: "Марс" },
  { english: "Earth", russian: "Земля" },
  { english: "Venus", russian: "Венера" },
  { english: "Jupiter", russian: "Юпитер" },
  { english: "moon", russian: "Луна" },
  { english: "Earth's core", russian: "ядро Земли" },
  { english: "ozone layer", russian: "озоновый слой" },
  { english: "incongruity", russian: "несоответствие" },
  { english: "loaf", russian: "булка; батон" },
  { english: "cupboard", russian: "буфет; шкаф" },
  { english: "to loaf", russian: "бездельничать; слоняться" },
  { english: "study", russian: "кабинет" },
  { english: "animal", russian: "животное; скот" },
  { english: "filthy animal", russian: "грязное животное" },
  { english: "pale", russian: "бледный; светлый" },
  { english: "cozy", russian: "уютный" },
  { english: "mild person", russian: "мягкий человек" },
  { english: "warm personality", russian: "теплый характер" },
  { english: "expressive", russian: "выразительный; эмоциональный" },
  { english: "glossy", russian: "глянцевый; блестящий" },
  { english: "rewarding", russian: "приносящий удовлетворение" },
  { english: "give off", russian: "испускать; отдавать" },
  {
    english: "tap",
    displayEnglish: "tap / to tap",
    acceptedAnswers: ["to tap"],
    russian: "кран; постукивать"
  },
  { english: "sticky", russian: "липкий; клейкий" },
  { english: "inner", russian: "внутренний" },
  { english: "surpassing", russian: "превосходящий; исключительный" },
  { english: "to retard", russian: "тормозить; задерживать" },
  { english: "to occur", russian: "случаться; происходить" },
  {
    english: "trap",
    displayEnglish: "trap / to trap",
    acceptedAnswers: ["to trap"],
    russian: "ловушка; капкан; заманивать"
  },
  { english: "bother", russian: "доставать; беспокоить" },
  { english: "survey", russian: "опрос; исследование" },
  { english: "twerp", russian: "придурок" },
  { english: "exposure", russian: "воздействие; разоблачение" },
  { english: "broadly", russian: "в широком смысле; в целом" },
  { english: "coursework", russian: "курсовая работа" },
  {
    english: "workflow",
    acceptedAnswers: ["work flow", "workflows"],
    russian: "рабочий процесс; схема работы"
  },
  { english: "seagull", acceptedAnswers: ["seagulls"], russian: "чайка" },
  { english: "shore", russian: "берег; побережье; край" },
  { english: "Northern Hemisphere", russian: "северное полушарие" },
  { english: "Southern Hemisphere", russian: "южное полушарие" },
  { english: "Eastern Hemisphere", russian: "восточное полушарие" },
  { english: "Western Hemisphere", russian: "западное полушарие" },
  { english: "Mercury", russian: "Меркурий" },
  { english: "Saturn", russian: "Сатурн" },
  { english: "Uranus", russian: "Уран" },
  { english: "Neptune", russian: "Нептун" },
  {
    english: "armour",
    displayEnglish: "armour / to armour",
    acceptedAnswers: ["armor", "to armor", "to armour"],
    russian: "броня; доспехи; защищать"
  },
  { english: "impenetrable", russian: "непроницаемый; непробиваемый" },
  {
    english: "sip",
    displayEnglish: "sip / to sip",
    acceptedAnswers: ["to sip"],
    russian: "глоток; пить маленькими глотками"
  },
  { english: "clubhouse", russian: "клубный дом" },
  {
    english: "hammer",
    displayEnglish: "hammer / to hammer",
    acceptedAnswers: ["to hammer"],
    russian: "молоток; бить; колотить"
  },
  { english: "disposal", russian: "удаление; утилизация; распоряжение" },
  { english: "blasphemous", russian: "богохульный; кощунственный" },
  { english: "dopefiend", russian: "наркоман; торчок" },
  {
    english: "jimmy",
    displayEnglish: "jimmy / to jimmy",
    acceptedAnswers: ["to jimmy"],
    russian: "взламывать; открывать силой"
  },
  { english: "to snap", russian: "щелкать; треснуть" },
  { english: "gross", russian: "мерзкий; грубый; отвратительный" },
  { english: "lame", russian: "хромой; слабый; тупой" },
  { english: "foreman", russian: "мастер; бригадир" },
  { english: "adverse", russian: "неблагоприятный; вредный" },
  { english: "eternity", russian: "вечность; бесконечность" },
  { english: "immature", russian: "незрелый; инфантильный" },
  { english: "skylarking", russian: "дурачество; баловство" },
  { english: "to skylark", russian: "дурачиться; резвиться" },
  { english: "tomfoolery", russian: "дурачество; шалости" },
  { english: "root", russian: "корень; основа; источник" },
  { english: "gossip", russian: "сплетни; слухи" },
  { english: "eager", russian: "стремящийся; жаждущий" },
  { english: "dove", russian: "голубь" },
  { english: "to beat", russian: "бить; побеждать" },
  { english: "beverage", russian: "напиток" },
  { english: "to acquaint", russian: "знакомить; осведомлять" },
  { english: "curfew", russian: "комендантский час" },
  { english: "sturdy", russian: "крепкий; прочный; надежный" },
  { english: "to hop in", russian: "быстро сесть; запрыгнуть внутрь" },
  { english: "to snuggle", russian: "прижиматься; уютно обниматься" },
  {
    english: "consent",
    displayEnglish: "consent / to consent",
    acceptedAnswers: ["to consent"],
    russian: "согласие; разрешение; соглашаться"
  },
  { english: "to thrive", russian: "процветать; расцветать" },
  { english: "appliance", russian: "бытовая техника" },
  { english: "lark", russian: "жаворонок" },
  { english: "wren", russian: "крапивник" },
  { english: "nest", russian: "гнездо" },
  { english: "cushion", acceptedAnswers: ["cushions"], russian: "диванная подушка" },
  { english: "peculiar", russian: "странный; необычный" },
  { english: "hazard", russian: "опасность; риск; угроза" },
  { english: "to nag", russian: "пилить; надоедать; ворчать" },
  { english: "tether", russian: "привязь; веревка" },
  { english: "particularly", russian: "особенно; в частности" },
  { english: "ongoing work", russian: "текущая работа" },
  { english: "disruption", russian: "нарушение; сбой" },
  { english: "slippery", russian: "скользкий" },
  { english: "bud", russian: "бутон" },
  { english: "lug", russian: "тащить; волочь" },
  { english: "valley", russian: "долина" },
  { english: "raiding", russian: "совершающий налет; нападающий" },
  { english: "defense", acceptedAnswers: ["defence"], russian: "защита; оборона" },
  { english: "mud", russian: "грязь; слякоть; ил" },
  { english: "savage", russian: "дикий; жестокий; свирепый" },
  { english: "intent", russian: "намерение; умысел" },
  { english: "indeed", russian: "действительно; в самом деле" },
  { english: "to untie", russian: "развязывать; отвязать" },
  { english: "customary", russian: "обычный; принятый; традиционный" },
  { english: "to kneel", russian: "встать на колени; преклонить колени" },
  { english: "tribe", russian: "племя; род" },
  { english: "heretic", russian: "еретик" },
  { english: "to condemn", russian: "осуждать; приговорить" },
  { english: "to herald", russian: "возвещать; предвещать; объявлять" },
  { english: "berry", russian: "ягода" },
  { english: "blizzard", russian: "метель; вьюга; снежный буран" },
  { english: "ancestor", russian: "предок; прародитель" },
  { english: "despite", russian: "несмотря на; вопреки" },
  { english: "to strike", russian: "ударять; поражать; наносить удар" },
  { english: "kite", russian: "воздушный змей; коршун" },
  { english: "magpie", russian: "сорока" },
  { english: "crane", russian: "журавль" },
  { english: "grief", russian: "горе; скорбь" },
  { english: "to grieve", russian: "горевать; скорбеть" },
  { english: "to get lost", russian: "заблудиться; потеряться" },
  { english: "complacency", russian: "самоуспокоение; беспечность" },
  { english: "eudaimonia", russian: "счастье; благополучие" },
  { english: "contentment", russian: "удовлетворенность; довольство" },
  { english: "to reminisce", russian: "предаваться воспоминаниям" },
  { english: "ridge", russian: "хребет; гребень" },
  { english: "rut", russian: "колея; рутина" },
  { english: "to unthink", russian: "раздумать; выбросить из головы" },
  { english: "pristine", russian: "нетронутый; безупречный" },
  { english: "beechwood", russian: "буковая древесина" },
  { english: "fiddle", russian: "скрипка; обман" },
  { english: "supplement", russian: "добавка; дополнение", group: 20 },
  { english: "ginkgo biloba", russian: "гинкго билоба", group: 20 },
  { english: "deficiency", russian: "недостаточность; дефицит", group: 20 },
  { english: "stimulant", russian: "стимул; возбуждающее", group: 20 },
  { english: "to consider", russian: "принимать во внимание; учитывать", group: 20 },
  { english: "impairment", russian: "нарушение; ухудшение; повреждение", group: 20 },
  { english: "impaired", russian: "нарушенный; ослабленный; поврежденный", group: 20 },
  { english: "rapid", russian: "быстрый; стремительный", group: 20 },
  { english: "reuptake", russian: "обратный захват", group: 20 },
  { english: "enhancing", russian: "усиливающий; улучшающий", group: 20 },
  { english: "to enhance", russian: "улучшать; усиливать; повышать", group: 20 },
  { english: "glug", russian: "бульканье; глоток", group: 20 },
  { english: "gut microbiome", russian: "кишечный микробиом", group: 21 },
  { english: "gut", russian: "кишечник", group: 21 },
  { english: "to overlook", russian: "не заметить; упустить", group: 21 },
  { english: "measurable", russian: "измеримый; заметный", group: 21 },
  { english: "reduction", russian: "снижение; уменьшение", group: 21 },
  { english: "inflammatory", russian: "воспалительный", group: 21 },
  { english: "to alleviate", russian: "облегчать; смягчать", group: 21 },
  { english: "odd", russian: "странный; необычный", group: 21 },
  { english: "higher odds", russian: "более высокие шансы", group: 21 },
  { english: "vicious", russian: "жестокий; злобный; свирепый", group: 21 },
  { english: "to fetch", russian: "принести; достать", group: 21 },
  { english: "pail", russian: "ведро", group: 21 },
  { english: "to tumble", russian: "падать; кувыркаться; валиться", group: 22 },
  { english: "tuffet", russian: "скамеечка; пучок травы", group: 22 },
  { english: "curds and whey", russian: "творог и сыворотка", group: 22 },
  { english: "to frighten", russian: "пугать; страшить", group: 22 },
  { english: "to alter", russian: "изменять; менять", group: 22 },
  { english: "to disrupt", russian: "разрывать; нарушать; срывать", group: 22 },
  { english: "to pump out", russian: "откачивать", group: 22 },
  { english: "properly", russian: "правильно; как следует", group: 22 },
  { english: "consistent", russian: "последовательный; совместимый", group: 22 },
  { english: "property", russian: "свойство; собственность", group: 22 },
  { english: "scale", russian: "масштаб; шкала; вес", group: 22 },
  { english: "salience", russian: "значимость; заметность", group: 22 },
  { english: "sustaining", russian: "поддерживающий; подпитывающий", group: 23 },
  { english: "trials", russian: "испытания; пробы", group: 23 },
  { english: "tumultuously", russian: "бурно; шумно", group: 23 },
  { english: "clustering up", russian: "сбиваясь в кучу; группируясь", group: 23 },
  { english: "wavering", russian: "колеблющийся; неуверенный", group: 23 },
  { english: "rubber", russian: "резина; каучук", group: 23 },
  { english: "ash", russian: "пепел", group: 23 },
  { english: "ink", russian: "чернила", group: 23 },
  { english: "to lay out", russian: "разложить; растянуть", group: 23 },
  { english: "sigh", russian: "вздох", group: 23 },
  { english: "squeak", russian: "пищать; поскрипывать", group: 23 },
  { english: "resilient", russian: "упругий; устойчивый", group: 23 },
  { english: "among", russian: "среди", group: 24 },
  { english: "tag", russian: "догонялки; салки", group: 24 },
  { english: "to squint", russian: "щуриться", group: 24 },
  { english: "to suspend", russian: "приостановить; откладывать", group: 24 },
  { english: "to savor", russian: "смаковать; наслаждаться", group: 24 },
  { english: "cave", russian: "пещера", group: 24 },
  { english: "to wail", russian: "выть; причитать", group: 24 },
  { english: "to hold out", russian: "протягивать; выдерживать", group: 24 },
  { english: "trembling", russian: "дрожащий", group: 24 },
  { english: "to cup", russian: "придавать чашевидную форму", group: 24 },
  { english: "to glance", russian: "взглянуть мельком", group: 24 },
  { english: "to fade", russian: "увядать; выцветать", group: 24 },
  { english: "mist", russian: "туман; дымка", group: 25 },
  { english: "startled", russian: "испуганный; пораженный", group: 25 },
  { english: "hurricane", russian: "ураган; буря; тропический циклон", group: 25 },
  { english: "flash", russian: "вспышка; блеск", group: 25 },
  { english: "avalanche", russian: "лавина; обвал", group: 25 },
  { english: "typist", russian: "машинистка", group: 25 },
  { english: "supper", russian: "ужин", group: 25 },
  { english: "jug", russian: "кувшин", group: 25 },
  { english: "great", russian: "великий", group: 25 },
  { english: "fleshlike", russian: "похожий на плоть", group: 25 },
  { english: "in the midst of", russian: "во время; посреди", group: 25 },
  { english: "standing in the open", russian: "стоящий на открытой местности", group: 25 },
  { english: "stir of mist", russian: "дымка; полоса тумана", group: 26 },
  { english: "to plunder", russian: "грабить; разграбить", group: 26 },
  { english: "let's ride", russian: "поскакали; поехали", group: 26 },
  { english: "to swallow", russian: "проглотить", group: 26 },
  { english: "dark", russian: "темный", group: 26 },
  { english: "darkness", russian: "темнота", group: 26 },
  { english: "without a trace", russian: "без следа", group: 26 },
  { english: "uncle", russian: "дядя", group: 26 },
  { english: "to shine", russian: "светить; сиять", group: 26 },
  { english: "to pat", russian: "похлопать", group: 26 },
  { english: "to prick", russian: "уколоть; проколоть", group: 26 },
  { english: "inbred", russian: "врожденный; инбредный", group: 26 },
  { english: "blackboard", russian: "доска для мела", group: 27 },
  { english: "butt", russian: "попа", group: 27 },
  { english: "ass", russian: "задница; осел", group: 27 },
  { english: "octopus", russian: "осьминог", group: 27 },
  { english: "octopi", russian: "осьминоги", group: 27 },
  { english: "arms", russian: "руки; щупальца", group: 27 },
  { english: "weed", russian: "сорняк", group: 27 },
  { english: "to flush the toilet", russian: "смывать воду в туалете", group: 27 },
  { english: "episode", russian: "эпизод", group: 27 },
  { english: "offended", russian: "обиженный", group: 27 },
  { english: "to offend", russian: "обидеть; оскорбить", group: 27 },
  { english: "to be scared of", russian: "бояться", group: 27 },
  { english: "to see his face", russian: "увидеть его лицо", group: 28 },
  { english: "to let it out", russian: "выпустить", group: 28 },
  { english: "to pull it out", russian: "вытащить", group: 28 },
  { english: "to ask for help", russian: "просить о помощи", group: 28 },
  { english: "at the same time", russian: "в то же время", group: 28 },
  { english: "to release", russian: "выпускать; освобождать", group: 28 },
  { english: "Aries", russian: "Овен", group: 29 },
  { english: "Taurus", russian: "Телец", group: 29 },
  { english: "Gemini", russian: "Близнецы", group: 29 },
  { english: "Cancer", russian: "Рак", group: 29 },
  { english: "Leo", russian: "Лев", group: 29 },
  { english: "Virgo", russian: "Дева", group: 29 },
  { english: "Libra", russian: "Весы", group: 29 },
  { english: "Scorpio", russian: "Скорпион", group: 29 },
  { english: "Sagittarius", russian: "Стрелец", group: 29 },
  { english: "Capricorn", russian: "Козерог", group: 29 },
  { english: "Aquarius", russian: "Водолей", group: 29 },
  { english: "Pisces", russian: "Рыбы", group: 29 },
  { english: "zodiac sign", russian: "знак зодиака", group: 30 },
  { english: "Pacific Ocean", russian: "Тихий океан", group: 30 },
  { english: "Atlantic Ocean", russian: "Атлантический океан", group: 30 },
  { english: "Indian Ocean", russian: "Индийский океан", group: 30 },
  { english: "Arctic Ocean", russian: "Северный Ледовитый океан", group: 30 },
  { english: "Southern Ocean", russian: "Южный океан", group: 30 },
  { english: "witness", russian: "свидетель; очевидец", group: 30 },
  { english: "glove box", russian: "бардачок в машине", group: 30 },
  { english: "edible", russian: "съедобный", group: 30 },
  { english: "to elongate", russian: "удлинять; вытягивать", group: 30 },
  { english: "curved", russian: "изогнутый; искривленный", group: 30 },
  { english: "starch", russian: "крахмал", group: 30 },
  { english: "rind", russian: "кожура; корка", group: 31 },
  { english: "ripe", russian: "спелый; зрелый", group: 31 },
  { english: "whale", russian: "кит", group: 31 },
  { english: "to curve", russian: "изгибать; искривлять", group: 31 },
  { english: "to execute", russian: "выполнять; осуществлять; казнить", group: 31 },
  { english: "fence", russian: "забор; изгородь; фехтование", group: 31 },
  { english: "to sift", russian: "просеивать; перебирать; анализировать", group: 31 },
  { english: "crack", russian: "трещина; раскол; хруст", group: 31 },
  {
    english: "to fill up",
    displayEnglish: "filling up / to fill up",
    acceptedAnswers: ["filling up", "fill up"],
    russian: "наполнять; заполнять; переполнять",
    group: 31
  },
  { english: "trench", russian: "траншея; ров; канава", group: 31 },
  { english: "to get loose", russian: "расслабиться; оторваться", group: 31 },
  { english: "tryna", acceptedAnswers: ["trying to"], russian: "пытаюсь; собираюсь; trying to", group: 31 },
  { english: "lit", russian: "крутой; огненный; зажигательный", group: 32 },
  { english: "to pop", russian: "лопнуть; щелкнуть; выстрелить", group: 32 },
  { english: "to pop out", russian: "выскочить; выйти; показаться", group: 32 },
  { english: "all out", russian: "по полной; целиком; изо всех сил", group: 32 },
  { english: "I done went", russian: "я уже ушел", group: 32 },
  { english: "to spazz out", russian: "взбеситься; сорваться; психануть", group: 32 },
  { english: "put the raw in", russian: "заняться сексом без презерватива", group: 32 },
  { english: "hit the strip club", russian: "сходить в стрип-клуб", group: 32 },
  {
    english: "Lil'",
    displayEnglish: "Lil' = little",
    acceptedAnswers: ["lil", "little"],
    russian: "сокращение от little",
    group: 32
  },
  { english: "shawty", russian: "малышка; малая; девчонка", group: 32 },
  { english: "Lil' shawty", acceptedAnswers: ["lil shawty"], russian: "малышка; красотка", group: 32 },
  {
    english: "Clicquot",
    displayEnglish: "Clicquot (Veuve Clicquot)",
    acceptedAnswers: ["veuve clicquot"],
    russian: "шампанское Клико",
    group: 32
  },
  { english: "heat stroke", russian: "тепловой удар", group: 33 },
  { english: "to lurk", russian: "ошиваться; таиться", group: 33 },
  { english: "through the peephole", russian: "через глазок", group: 33 },
  { english: "to hit", acceptedAnswers: ["hit"], russian: "бить; ударять; заходить", group: 33 },
  { english: "to waver", russian: "колебаться; дрожать", group: 33 },
  { english: "brand new", russian: "совершенно новый", group: 33 },
  { english: "raw", russian: "сырой; необработанный; грубый", group: 33 },
  { english: "to sweep up", russian: "подметать; сметать; убирать", group: 33 },
  { english: "to mend", russian: "чинить; исправлять", group: 33 },
  { english: "kettle", russian: "чайник; котелок", group: 33 },
  { english: "hearth", russian: "очаг; камин", group: 33 },
  { english: "dreary", russian: "унылый; мрачный; серый", group: 33 },
  { english: "o'er", russian: "над; через; сверх", group: 34 },
  { english: "apace", russian: "быстро; стремительно", group: 34 },
  { english: "stout", russian: "плотный; тучный; крепкий", group: 34 },
  { english: "bosom", russian: "грудь; пазуха; душа", group: 34 },
  { english: "toil", russian: "тяжелый труд; изнурительный труд", group: 34 },
  { english: "hardship", russian: "трудность; лишение", group: 34 },
  { english: "austere", russian: "суровый; аскетичный; строгий", group: 34 },
  { english: "hath", russian: "устаревшая форма has", group: 34 },
  { english: "shutter", russian: "ставня; затвор", group: 34 },
  { english: "lane", russian: "переулок; дорожка; аллея", group: 34 },
  { english: "plain", russian: "простой; ясный; очевидный; равнина", group: 34 },
  { english: "threshold", russian: "порог; граница; начало", group: 34 },
  { english: "to stack", russian: "складывать в стопку; укладывать", group: 35 },
  {
    english: "C-note",
    displayEnglish: "C-note / C-notes",
    acceptedAnswers: ["c note", "c-notes", "c notes"],
    russian: "сотка; сто долларов",
    group: 35
  },
  { english: "to give it your all", russian: "выкладываться; отдавать все силы", group: 35 },
  { english: "nameless", russian: "безымянный; неизвестный", group: 35 },
  { english: "to fall back", russian: "отступить; падать назад", group: 35 },
  { english: "all that", russian: "крутой; особенный; прям очень", group: 35 },
  { english: "dashboard", russian: "приборная панель", group: 35 },
  { english: "It ain't like", russian: "это не так; не то чтобы", group: 35 },
  { english: "to pack", russian: "упаковывать; наполнять", group: 35 },
  { english: "to throw a party", russian: "устраивать вечеринку", group: 35 },
  {
    english: "'bout",
    displayEnglish: "'bout = about",
    acceptedAnswers: ["bout", "about"],
    russian: "насчет; about",
    group: 35
  },
  { english: "foreign", russian: "иностранный; зарубежный", group: 35 },
  { english: "clingy", russian: "липкий; навязчивый", group: 36 },
  { english: "bursting", russian: "лопающийся; переполненный; разрывающийся", group: 36 },
  { english: "peril", russian: "опасность; риск; угроза", group: 36 },
  { english: "untiring", russian: "неутомимый; неустанный", group: 36 },
  { english: "honour", acceptedAnswers: ["honor"], russian: "честь; почет; уважение", group: 36 },
  { english: "duty", russian: "долг; обязанность; служба", group: 36 },
  { english: "to seize", russian: "схватить; завладеть", group: 36 },
  { english: "stream", russian: "ручей; поток; струя", group: 36 },
  { english: "to burst", russian: "лопнуть; взорваться; прорваться", group: 36 },
  { english: "to trip", russian: "споткнуться; идти легкой походкой", group: 36 },
  { english: "to honour", acceptedAnswers: ["to honor"], russian: "чтить; почитать; выполнять", group: 36 },
  { english: "a peck of", russian: "много; большое количество", group: 36 },
  { english: "to pickle", russian: "мариновать; засолить", group: 37 },
  { english: "to wag", russian: "вилять; махать", group: 37 },
  { english: "dozen", russian: "дюжина", group: 37 },
  { english: "baker's dozen", russian: "чертова дюжина; 13 штук", group: 37 },
  { english: "to cluster", russian: "группироваться; собирать в группу", group: 37 }
];
